name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Format Check
        run: cargo fmt --all --check
      
      - name: Lint Check
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Build
        run: cargo build --release
      
      - name: Test
        run: cargo test --all
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-init-cli-${{ runner.os }}
          path: ${{ matrix.os == 'windows-latest' && './target/release/github-init-cli.exe' || './target/release/github-init-cli' }}
          retention-days: 1
  
  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract Version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          files:
            - ./artifacts/github-init-cli-Linux/github-init-cli
            - ./artifacts/github-init-cli-Windows/github-init-cli.exe
            - ./artifacts/github-init-cli-macOS/github-init-cli